version: '3.4'

services:
  digitalwallet:
    image: ${DOCKER_REGISTRY-}digitalwallet
    build:
      context: .
      dockerfile: DigitalWallet/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sql-database
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql-database;Database=DigitalWalletDb;User Id=sa;Password=HarikaProjem123!;TrustServerCertificate=True;
      - JwtSettings__SecretKey=BenimCokGizliAnahtarim_ProjelerIcin_123

  sql-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HarikaProjem123!
    ports:
      - "1433:1433"
